title: "OpenTRNG"
logo: "/assets/images/logo.png"
url: "https://opentrng.org"
description: "This project is dedicated to delivering the community open-source implementations of reference Physical TRNG."
repository: "opentrng/ptrng"

breadcrumbs: false
show_date: false
search: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/opentrng"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/florian-pebay-peyroula/"
    - label: "CEA-Leti"
      icon: "fas fa-fw fa-link"
      url: "https://www.cea-leti.fr"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

lunr:
  search_within_pages: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-7XE6GB2SY9"
    anonymize_ip: false

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "sidebar"
